[package]
name = "bevy_unified_input"
version = "0.3.0"
authors = ["Oleks Pickle <22867443+olekspickle@users.noreply.github.com>"]
description = "A unified input primitives"
keywords = ["bevy", "inoput"]
categories = ["game-development"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/olekspickle/bevy_unified_input"
homepage = "https://github.com/olekspickle/bevy_unified_input"
readme = "README.md"
edition = "2024"

[dependencies]
bevy_input = { version = "0.19", features = ["gamepad", "mouse", "keyboard"] }
bevy_ecs = { version = "0.19", default-features = false }

[dev-dependencies.bevy]
version = "0.19"
default-features = false
features = [ "3d", "ui", "debug" ]


[features]
default = []

